# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: get current kernel
  command: uname -r
  register: unamer
  changed_when: false

- name: check if kernel-(rt-)devel is already installed
  shell: >
    set -o pipefail &&
    yum list installed | grep -E "kernel-(rt-)?devel(.*){{ '.'.join(unamer.stdout.split('.')[:-1]) }}"
  register: yum_list_kernel_devel
  failed_when: false
  changed_when: false

- name: install kernel-devel package
  block:
  - name: use kernel-devel-uname-r
    set_fact:
      kernel_devel_to_install: "kernel-devel-uname-r == {{ unamer.stdout }}"
  - name: use kernel-devel from provided URL/package
    set_fact:
      kernel_devel_to_install: "{{ dpdk_kernel_devel }}"
    when:
    - dpdk_kernel_devel is defined
    - dpdk_kernel_devel|length > 0

  - name: fail if kernel-devel version is not correct
    fail:
      msg: "kernel-devel version({{ kernel_devel_to_install }}) does not match the current kernel({{ unamer.stdout }})"
    when: 'unamer.stdout not in kernel_devel_to_install'

  - name: install kernel-devel package
    yum:
      name: "{{ kernel_devel_to_install }}"
      state: present
      disable_excludes: all
      allow_downgrade: true
    retries: "{{ number_of_retries }}"
    delay: "{{ retry_delay }}"
  # install kernel-devel package if:
  # - kernel_package is not defined = `custom_kernel` role is commented (disabled), OR
  # - kernel_skip is defined and kernel_skip = `custom_kernel` is enabled, but `kernel_skip` is true
  when:
  - (kernel_package is not defined) or (kernel_skip is defined and kernel_skip)
  - yum_list_kernel_devel.rc == 1   # kernel-(rt-)devel is missing

- name: check if already installed
  stat:
    path: "{{ _acc100_dpdk_install_dir }}"
  register: _acc100_dpdk_dest_dir

- name: download
  get_url:
    url: "{{ _acc100_dpdk_download_url }}"
    dest: "{{ _acc100_dpdk_download_dest }}"
    checksum: "md5:{{ _acc100_dpdk_checksum }}"
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"
  when: not _acc100_dpdk_dest_dir.stat.exists

- name: ensure install dir exists
  file:
    path: "{{ _acc100_dpdk_install_dir }}"
    state: directory
    mode: a=rx,u+w

- name: extract
  unarchive:
    src: "{{ _acc100_dpdk_download_dest }}"
    dest: "{{ _acc100_dpdk_install_dir }}"
    extra_opts: "--strip-components=1"
    remote_src: true
    creates: "{{ _acc100_dpdk_install_dir }}/README"

- name: check if already compiled
  stat:
    path: "{{ _acc100_dpdk_install_dir }}/build/app/dpdk-test-bbdev"
  register: dpdk_test_bbdev

- name: install numactl-devel
  yum:
    name: "{{ item }}"
    state: present
  retries: "{{ number_of_retries }}"
  delay: "{{ retry_delay }}"
  loop:
    - numactl-devel
    - meson
  when: not dpdk_test_bbdev.stat.exists

- name: compile
  shell: meson build && cd build && ninja
  args:
    chdir: "{{ _acc100_dpdk_install_dir }}"
  when: not dpdk_test_bbdev.stat.exists
