# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ovn4nfv-k8s-plugin.yaml
- ovn-daemonset.yaml

patchesJson6902:
- target:
    version: v1
    kind: DaemonSet
    name: ovn4nfv-cni
  path: customize-ovn4nfv-cni-container.yml
- target:
    version: v1
    kind: DaemonSet
    name: nfn-agent
  path: customize-nfn-agent-container.yml 
- target:
    version: v1
    kind: Deployment
    name: nfn-operator
  path: customize-nfn-operator-container.yml
- target:
    version: v1
    kind: Deployment
    name: ovn-control-plane
  path: customize-ovn-control-plane-container.yml
- target:
    version: v1
    kind: DaemonSet
    name: ovn-controller
  path: customize-ovn-controller-container.yml
 
patchesStrategicMerge:
- customize-nodus-cidr.yml
- customize-ovn4nfv-container-proxy.yml

