# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
# tuned_version: "*"
tuned_version: "2.11.0-10.el7.noarch"

tuned_centos79_packages:
  - http://linuxsoft.cern.ch/scientific/7x/x86_64/os/Packages/tuned-2.11.0-9.el7.noarch.rpm
  - http://linuxsoft.cern.ch/scientific/7x/x86_64/os/Packages/tuned-profiles-realtime-2.11.0-9.el7.noarch.rpm

tuned_profile_common: realtime
tuned_profile_centos7: realtime-virtual-host

# Following two isolcpus* params are common with role configure_cpu_isolation
isolcpus_enabled: true
isolcpus: "2-3"
