# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: validate default hugepage size setting
  assert: {that: default_hugepage_size == "2M" or default_hugepage_size == "1G"}

- name: Fail when trying to pre-allocate hugepages of multiple page sizes
  fail:
    msg: "Kubelet does not support pre-allocated hugepages for multiple page sizes."
  when:
  - hugepages_1G > 0
  - hugepages_2M > 0

- name: validate that any hugepages of default size are requested
  assert: {that: hugepages_1G > 0}
  when:
    - default_hugepage_size == "1G"

- name: validate that any hugepages of default size are requested
  assert: {that: hugepages_2M > 0}
  when:
    - default_hugepage_size == "2M"

- name: calculate total number of requested hugepages
  set_fact:
    mem_huge_2M: "{{ hugepages_2M|default(0) * 2 }}"
    mem_huge_1G: "{{ hugepages_1G|default(0) * 1024 }}"

- name: assert that there's enough memory on the target system for the requested hugepages
  assert:
    that: (mem_huge_2M|int + mem_huge_1G|int) < (ansible_memtotal_mb|int - mem_reserved|int)
    msg: "Requested {{ mem_huge_2M|int + mem_huge_1G|int }}MB of hugepages, while {{ ansible_memtotal_mb|int - mem_reserved|int }}MB is available."

- name: set hugepages kernel boot flags
  set_fact:
    hugepages_flags: >-
      default_hugepagesz={{ default_hugepage_size }}
      {% if hugepages_1G > 0 %}hugepagesz=1G hugepages={{ hugepages_1G | int }}{% endif %}
      {% if hugepages_2M > 0 %}hugepagesz=2M hugepages={{ hugepages_2M | int }}{% endif %}

- name: prepare hugepages grub commandline string
  set_fact:
    hugepages_cmdline: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} {{ hugepages_flags }}" {{ hugepages_marker }}'

- name: set hugepages flags in /etc/default/grub
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="\${GRUB_CMDLINE_LINUX}(.*?)" {{ hugepages_marker }}$'
    line: '{{ hugepages_cmdline }}'
    state: present
    mode: a=r,u+w,g+w
  register: grub
  become: yes
