# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: verify inventory
  block:
  - name: fail if `edgenode_group` doesn't contain only one node
    fail:
      msg: |
        For single-node Network Edge deployment `edgenode_group` group in the inventory.yml should contain only one node, e.g.:

        # inventory.yml file
        edgenode_group:
          hosts:
            node01:
              ansible_host: {{ hostvars[groups['controller_group'][0]]['ansible_host'] }}
              ansible_user: {{ hostvars[groups['controller_group'][0]]['ansible_user'] }}
    when:
    - groups['edgenode_group'] is defined
    - groups['edgenode_group'] | length != 1

  - name: fail if controller and node are not the same machine
    fail:
      msg: |
        For single-node Network Edge deployment Controller and Node should be the same machine (i.e. same IP address), e.g.

        # inventory.yml file
        controller_group:
          hosts:
            controller:
              ansible_host: {{ hostvars[groups['controller_group'][0]]['ansible_host'] }}
              ansible_user: {{ hostvars[groups['controller_group'][0]]['ansible_user'] }}
        edgenode_group:
          hosts:
            node01:
              ansible_host: {{ hostvars[groups['controller_group'][0]]['ansible_host'] }}
              ansible_user: {{ hostvars[groups['controller_group'][0]]['ansible_user'] }}
    when:
    - hostvars[groups['controller_group'][0]]['ansible_host'] != hostvars[groups['edgenode_group'][0]]['ansible_host']

  - name: fail if controller and node are not different entries in the inventory
    fail:
      msg: |
        For single-node Network Edge deployment should be different entries with the same IP address, e.g.:

        # inventory.yml file
        controller_group:
          hosts:
            controller:
              ansible_host: {{ hostvars[groups['controller_group'][0]]['ansible_host'] }}
              ansible_user: {{ hostvars[groups['controller_group'][0]]['ansible_user'] }}
        edgenode_group:
          hosts:
            node01:
              ansible_host: {{ hostvars[groups['controller_group'][0]]['ansible_host'] }}
              ansible_user: {{ hostvars[groups['controller_group'][0]]['ansible_user'] }}
    when:
    - groups['controller_group'][0] == groups['edgenode_group'][0]

  - name: fail if controller and node are deployed using different user
    fail:
      msg: |
        For single-node deployment controller and node entries should use the same user, e.g.:

        # inventory.yml file
        controller_group:
          hosts:
            controller:
              ansible_host: {{ hostvars[groups['controller_group'][0]]['ansible_host'] }}
              ansible_user: {{ hostvars[groups['controller_group'][0]]['ansible_user'] }}
        edgenode_group:
          hosts:
            node01:
              ansible_host: {{ hostvars[groups['controller_group'][0]]['ansible_host'] }}
              ansible_user: {{ hostvars[groups['controller_group'][0]]['ansible_user'] }}
    when:
    - hostvars[groups['controller_group'][0]]['ansible_user'] != hostvars[groups['edgenode_group'][0]]['ansible_user']
