# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: Check if Secure Boot enabled
  shell: "set -o pipefail && bootctl status 2> /dev/null | grep 'Secure Boot: enabled' > /dev/null"
  register: secure_boot_status
  become: yes
  changed_when: false
  failed_when: false

- name: label controlplane node as suefi enabled
  command: "kubectl label --overwrite node {{ ansible_nodename | lower }} node.type=SUEFI-ENABLED"
  delegate_to: "{{ groups['controller_group'][0] }}"
  when: secure_boot_status.rc == 0
