# INTEL CONFIDENTIAL
#
# Copyright 2020-2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
# Playbook for single node Network Edge cluster deployment

- hosts: edgenode_group
  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}
    - name: create helper variable
      set_fact:
        single_node_deployment: true

- name: Deploy single node infrastructure
  import_playbook: opendek/single_node_network_edge.yml

- name: Provision target infrastructure
  import_playbook: playbooks/infrastructure.yml

- name: Provision Kubernetes cluster
  import_playbook: playbooks/kubernetes.yml

- name: Provision Applications
  import_playbook: playbooks/applications.yml
