# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

install_dependencies:
  Debian:
    - libgpgme-dev
    - libassuan-dev
    - libbtrfs-dev
    - libdevmapper-dev
    - pkg-config
  RedHat:
    - gpgme-devel
    - device-mapper-devel
    - libassuan-devel
