# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

# Default values for hvs-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: isecl

basename: ihub

image:
  repository: isecl/ihub
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v4.1.1"

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  runAsUser: 1001
  runAsGroup: 1001

resources:
  requests:
    storage: 1Gi

ihubConfiguration:
  TLS_SAN_LIST: ihub-svc.isecl.svc.cluster.local,edge-worker-node
  HVS_BASE_URL: https://hvs-svc.isecl.svc.cluster.local:8443/hvs/v2
  AAS_API_URL: https://aas-svc.isecl.svc.cluster.local:8444/aas/v1
  CMS_BASE_URL: https://cms-svc.isecl.svc.cluster.local:8445/cms/v1
  CMS_TLS_CERT_SHA384:
  TENANT: KUBERNETES
  KUBERNETES_URL:
  KUBERNETES_CRD: custom-isecl
  KUBERNETES_CERT_FILE: /apiserver.crt
  KUBERNETES_TOKEN:

proxyConfig:
  - name: http_proxy
    value: <http_proxy>
  - name: https_proxy
    value: <https_proxy>
  - name: all_proxy
    value: <all_proxy>
  - name: no_proxy
    value: <no_proxy>

persistentVolumeConfig:
  storageClassName: nfs
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    confPath: <nfs-client-mount-path>/isecl/ihub/config
    logsPath: <nfs-client-mount-path>/isecl/ihub/logs
    server: <nfs-server-ip/nfs-server-hostname>
  requests:
      storage: 128Mi
  logStorage: 1Gi

volumeConfig:
  ihubConfigPath: /etc/ihub/
  ihubLogsPath: /var/log/ihub/
  ihubSecretsPath: /etc/secrets/

