# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2021 Intel Corporation

---
- name: wait for controller's time setup with NTP
  stat:
    path: "{{ ntp_time_set }}"
  register: ntp_contoller_result
  delegate_to: "{{ reference_host }}"
  until: ntp_contoller_result.stat.exists
  retries: 60
  delay: 10
  when: ntp_enable | default(False)

- name: wait for node time setup with NTP
  stat:
    path: "{{ ntp_time_set }}"
  register: ntp_node_result
  until: ntp_node_result.stat.exists
  retries: 60
  delay: 10
  when: ntp_enable | default(False)

- name: get controller's date
  command: date +%s
  register: controller_date
  delegate_to: "{{ reference_host }}"
  changed_when: false

- name: get node's date
  command: date +%s
  register: node_date
  changed_when: false

- name: calculate absolute time difference
  set_fact:
    ntp_time_difference: "{{ ((node_date.stdout | int) - (controller_date.stdout | int)) | abs }}"

- name: fail if time difference exceeds threshold
  fail:
    msg: "The date difference between Edge Controller and Edge Node is too big. Please update time on both machines and retry the installation scripts."
  when: (ntp_time_difference | int) > date_threshold_seconds
