# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: add Docker repository
  yum_repository:
    name: docker
    description: Docker CE repository
    baseurl: "{{ _docker_repository_url }}"
    gpgkey: "{{ _docker_repository_key }}"
    gpgcheck: true
  become: yes
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"

- name: clear yum cache
  command: yum clean all
  args:
    warn: false
  changed_when: true
