# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- block:
    - name: Deploy Intel Device plugin operator using pre-built image
      command: kubectl apply -k {{ _git_repo_device_plugin_operator }}
      changed_when: true

    - name: Wait for Intel Device plugin operator pods to be ready
      command: kubectl wait --for=condition=Ready pods --all --namespace=inteldeviceplugins-system --timeout=2m
      changed_when: true
      register: intel_device_plugin_operator

    - name: Deploy SGX device plugin with the operator using pre-built image
      command: kubectl apply -f {{ _git_repo_sgx_device_plugin }}
      changed_when: true
  when: ansible_os_family == "Debian"

