# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- name: Remove old repository folder
  file:
    path: "{{ git_repo_dest }}"
    state: absent

- name: clean git http proxy
  git_config:
    name: http.proxy
    scope: global
    state: absent
  when: git_http_proxy | length > 0
  failed_when: false
