# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---
- name: create temporary custom git config
  include_tasks: ./gitconfig_bootstrap.yml

- name: online mode
  block:
    - name: "Check Git configuration"
      debug:
        msg: "Using git token for repository checkout"
      when: git_repo_token|length > 0

    - name: checkout clean repository - "{{ git_repo_url }}"
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_dest }}"
        version: "{{ git_repo_branch }}"
        accept_hostkey: true
        force: yes
      register: result
      when: always_clean_repository
      retries: "{{ number_of_retries | default(5) }}"
      until: result is succeeded
      delay: "{{ retry_delay | default(5) }}"

    - name: make sure repository exists
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_dest }}"
        version: "{{ git_repo_branch }}"
        accept_hostkey: true
        update: false
      when: not always_clean_repository

  always:
    - name: remove custom git config
      include_tasks: ./gitconfig_remove.yml
