# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: get kubelet info
  systemd:
    name: kubelet
  register: kubelet_status

- name: get process run time
  command: ps -p {{ kubelet_status.status.MainPID  }} -o etimes=
  register: kubelet_run_time
  changed_when: false

- name: kubelet service should be running
  assert:
    that:
      - "'running' in kubelet_status.status.SubState"
      - kubelet_run_time.stdout | int > 60
    success_msg: "kubelet service is OK"
    fail_msg: "kubelet service is either not running or its running time is less than 60 seconds"
