# Copyright (C) 2021  Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.daemonSetName }}-config
  namespace: {{ .Values.namespace }}
data:
  {{- toYaml .Values.taConfiguration | nindent 2 }}
  
  
