# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

{{- if .Values.rollback.enabled -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ta.fullname" . }}-rollback
  namespace: {{ .Values.namespace }}
  labels:
    run-once-daemonset: {{ include "ta.fullname" . }}-rollback
spec:
  selector:
    matchLabels:
      run-once-daemonset: {{ include "ta.fullname" . }}-rollback
  template:
    metadata:
      labels:
        run-once-daemonset: {{ include "ta.fullname" . }}-rollback
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.type
                    operator: In
                    values:
                      - "TXT-ENABLED"
                      - "SUEFI-ENABLED"
      initContainers:
        {{- toYaml .Values.rollback.initContainer | nindent 8 }}
          volumeMounts:
            - name: ta-volume
              mountPath: {{ .Values.volumeConfiguration.taVolume.mountPath }}
            - name: ta-backup-volume
              mountPath: {{ .Values.volumeConfiguration.taBackupVolume.mountPath }}
      containers:
        - name: pause
          image: {{ .Values.pauseContainerImage }}
      volumes:
        - name: ta-volume
          hostPath:
            path: {{ .Values.volumeConfiguration.taVolume.hostPath }}
            type: {{ .Values.volumeConfiguration.taVolume.type }}
        - name: ta-backup-volume
          hostPath:
            path: {{ .Values.volumeConfiguration.taBackupVolume.hostPath }}
            type: {{ .Values.volumeConfiguration.taBackupVolume.type }}
...
{{- end }}
