# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

{{- if .Values.upgrade.enabled -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ta.fullname" . }}-upgrade
  namespace: {{ .Values.namespace }}
  labels:
    run-once-daemonset: {{ include "ta.fullname" . }}-upgrade
spec:
  selector:
    matchLabels:
      run-once-daemonset: {{ include "ta.fullname" . }}-upgrade
  template:
    metadata:
      labels:
        run-once-daemonset: {{ include "ta.fullname" . }}-upgrade
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.type
                    operator: In
                    values:
                      - "TXT-ENABLED"
                      - "SUEFI-ENABLED"
      initContainers:
        {{- toYaml .Values.upgrade.initContainer | nindent 8 }}
          volumeMounts:
            - name: ta-volume
              mountPath: {{ .Values.volumeConfiguration.taVolume.mountPath }}
            - name: ta-backup-volume
              mountPath: {{ .Values.volumeConfiguration.taBackupVolume.mountPath }}
        - name: ta-upgrade
          {{- toYaml .Values.upgrade.container | nindent 8 }}
          env:
            - name: CONFIG_DIR
              value: {{ .Values.upgrade.environment.configDir }}
            - name: COMPONENT_VERSION
              value: {{ .Values.upgrade.environment.componentVersion }}
          volumeMounts:
          - name: ta-logs-volume
            mountPath: {{ .Values.volumeConfiguration.taLogsVolume.mountPath }}
          - name: ta-volume
            mountPath: {{ .Values.volumeConfiguration.taVolume.mountPath }}
          - name: tpmrm
            mountPath: {{ .Values.volumeConfiguration.tpmrm.mountPath }}
          - name: ta-credentials
            mountPath: {{ .Values.volumeConfiguration.taCredentials.mountPath }}
      containers:
        - name: pause
          image: {{ .Values.pauseContainerImage }}
      volumes:
        - name: ta-logs-volume
          hostPath:
            path: {{ .Values.volumeConfiguration.taLogsVolume.hostPath }}
            type: {{ .Values.volumeConfiguration.taLogsVolume.type }}
        - name: ta-volume
          hostPath:
            path: {{ .Values.volumeConfiguration.taVolume.hostPath }}
            type: {{ .Values.volumeConfiguration.taVolume.type }}
        - name: tpmrm
          hostPath:
            path: {{ .Values.volumeConfiguration.tpmrm.hostPath }}
        - name: ta-credentials
          secret:
            secretName: ta-secret
        - name: ta-backup-volume
          hostPath:
            path: {{ .Values.volumeConfiguration.taBackupVolume.hostPath }}
            type: {{ .Values.volumeConfiguration.taBackupVolume.type }}
...
{{- end }}
