# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2021 Intel Corporation

---

- name: open firewall rules
  include_role:
    name: infrastructure/firewall_open_ports
  vars:
    fw_open_ports: "{{ ovn4nfv_open_ports }}"

- name: ovn4nfv | Label control-plane node
  command: >-
    kubectl label --overwrite node {{ ansible_nodename }}
    ovn4nfv-k8s-plugin=ovn-control-plane
  changed_when: true

- name: create tmp dir
  tempfile:
    state: directory
    suffix: -ovn4nfv
  register: tmp_dir

- name: ovn4nfv | Create ovn4nfv-k8s manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ tmp_dir.path }}/{{ item.file }}"
    mode: preserve
  loop:
    - {name: ovn-daemonset, file: ovn-daemonset.yml}
    - {name: ovn4nfv-k8s-plugin, file: ovn4nfv-k8s-plugin.yml}
    - {name: customize_ovn4nfv_container, file: customize_ovn4nfv_container.yml}
  register: ovn4nfv_node_manifests

- name: copy kustomization.yml
  copy:
    src: "{{ item }}"
    dest: "{{ tmp_dir.path }}"
    mode: preserve
  loop:
    - kustomization.yml

- name: apply ovn-daemonset.yml
  command: kubectl apply -f ovn-daemonset.yml
  args:
    chdir: "{{ tmp_dir.path }}"
  changed_when: true

- name: check if proxy is enabled
  set_fact:
    _proxy_enabled: >
      {{ proxy_env is defined and
         (('http_proxy' in proxy_env and proxy_env['http_proxy'] | length) or
          ('https_proxy' in proxy_env and proxy_env['https_proxy'] | length) or
          ('ftp_proxy' in proxy_env and proxy_env['ftp_proxy'] | length) | bool) | default(False) }}

- name: apply ovn4nfv-k8s-plugin.yml
  block:
    - name: apply file with no change
      command: kubectl apply -f ovn4nfv-k8s-plugin.yml
      args:
        chdir: "{{ tmp_dir.path }}"
      changed_when: true
  when: not _proxy_enabled

- name: apply ovn4nfv-k8s-plugin.yml with change
  block:
    - name: apply file with change
      shell: >
        set -o pipefail &&
        kubectl kustomize . | kubectl apply -f -
      args:
        chdir: "{{ tmp_dir.path }}"
      changed_when: true
  when: _proxy_enabled

- name: apply ovn4nfv's NetworkAttachmentDefinition
  block:
    - name: copy NetworkAttachmentDefinition to remote
      template:
        src: attach-network-ovn.yml
        dest: "{{ tmp_dir.path }}/attach-network-ovn.yml"
        mode: preserve
    - name: apply ovn4nfv's NetworkAttachmentDefinition
      command: kubectl apply -f {{ tmp_dir.path }}/attach-network-ovn.yml
  when:
    - apply_netdef is defined
    - apply_netdef
