# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-statsd-exporter.fullname" . }}
  labels:
    {{- include "prometheus-statsd-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.proxy.metricsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.statsd.tcpPort }}
      targetPort: statsd-tcp
      protocol: TCP
      name: statsd-tcp
    - port: {{ .Values.statsd.udpPort }}
      targetPort: statsd-udp
      protocol: UDP
      name: statsd-udp
  selector:
    {{- include "prometheus-statsd-exporter.selectorLabels" . | nindent 4 }}
