# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: remove additional_grub_parameter settings when setting is disabled
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=(.*?){{ additional_grub_parameters_marker }}$'
    state: absent
  register: grub
  become: yes
  when: not additional_grub_parameters_enabled

- name: setup additional grub parameters
  include_tasks: setup_additional_grub_parameters.yml
  when:
    - additional_grub_parameters_enabled

# noqa because include_role cannot be used in a handler
- name: update grub  # noqa no-handler
  include_role:
    name: infrastructure/update_grub
  when:
    - grub.changed
