# INTEL CONFIDENTIAL
#
# Copyright 2020-2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
# This file contains variables intended to be configured by user.
# It allows feature enabling and configuration.
# Features should not be configured by changing roles' defaults (i.e. role/defaults/main.yml)

### Network Edge's Kubernetes CNIs
# List of requested CNIs to be used in Network Edge mode
# CNIs are applied in order of definition
# Multus CNI is implicit - it will be applied as 2nd one if list contains more than 1
# Available CNIs:
# - calico (note: if the calico CNI is used, then it must be main/primary CNI, i.e. first on the list)
# - nodus (note: nodsus as main/primary CNI is not supported)
kubernetes_cnis:
  - calico
  - nodus

# Nodus CIDR
nodus_cidr: "10.210.0.0/16"

icn_cnf_ip_suffix: 19