# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2021 Intel Corporation

---
- name: check if Prometheus release already exists
  command: helm status prometheus -n {{ telemetry_namespace }}
  failed_when: false
  register: get_release_prometheus
  changed_when: false

- name: install Prometheus chart
  include_tasks: install_prometheus.yml
  when: get_release_prometheus.rc != 0

- name: setup additional monitors
  include_tasks: setup_additional_monitors.yml
