# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

_docker_os_dependencies: "gcc,python2-pip,python2-devel,python3-pip,device-mapper-persistent-data,lvm2,moreutils,jq"
