# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

---

- name: create temporary directory
  tempfile:
    state: directory
    suffix: kubevirt-operator
  register: tmp_dir

- name: Download kubevirt controller
  get_url:
    url: "{{ _kubevirt_cr_url }}"
    dest: "{{ tmp_dir.path }}/kubevirt-cr.yaml"
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"

- name: Download KV Operator
  get_url:
    url: "{{ _kubevirt_operator_url }}"
    dest: "{{ tmp_dir.path }}/virt-operator.yaml"
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"

- name: template kustomization.yml to tmp directory
  template:
    src: kustomization.yml.j2
    dest: "{{ tmp_dir.path }}/kustomization.yml"
    mode: u+rw
  loop:
    - virt

- name: KV Operator Install
  command: kubectl apply -k .
  args:
    chdir: "{{ tmp_dir.path }}"
  changed_when: true

- name: KV Controller Install
  command: kubectl apply -f "{{ tmp_dir.path }}/kubevirt-cr.yaml"
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"
  changed_when: true

- name: remove temporary directory
  file:
    path: "{{ tmp_dir.path }}"
    state: absent
  when: tmp_dir.path is defined
