# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

---

- name: create temporary directory
  tempfile:
    state: directory
    suffix: virtctl
  register: tmp_dir

- name: download virtctl repo
  get_url:
    url: "{{ _virtctl_url }}"
    dest: "{{ tmp_dir.path }}/{{ _virtctl_tar }}"
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"

- name: Unarchive virtctl
  unarchive:
    src: "{{ tmp_dir.path }}/{{ _virtctl_tar }}"
    dest: "{{ tmp_dir.path }}"
    remote_src: yes

- name: Install virt
  copy:
    src: "{{ tmp_dir.path }}/virtctl/virtctl-linux-amd64"
    dest: "{{ _virtctl_dir }}/{{ _virtctl_name }}"
    remote_src: yes
    mode: a=rx,u+w
  become: yes

- name: remove temporary directory
  file:
    path: "{{ tmp_dir.path }}"
    state: absent
  when: tmp_dir.path is defined
