# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: update grub.cfg
  command: update-grub
  changed_when: true
  become: yes
  when:
    - ansible_os_family == "Debian"
  notify:
    - reboot server
