# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
# 2-27
- name: autogenerate isolcpu physical range for socket 1
  set_fact:
    isolcpus: "{{ cmk_exclusive_num_cores }}\
              -{{ ansible_processor_cores -1 }}"
  when: cmk_exclusive_num_cores is defined

# 30-55
- name: autogenerate isolcpu logical range for socket 1 hyperthread enabled
  set_fact:
    isolcpus: "{{ isolcpus }}\
              ,{{ ansible_processor_cores + cmk_exclusive_num_cores }}\
              -{{ ansible_processor_cores * ansible_processor_threads_per_core - 1 }}"
  when:
    - cmk_exclusive_num_cores is defined
    - ansible_processor_threads_per_core > 1

# 30-55
- name: autogenerate isolcpu physical range for socket 2 hyperthread disabled
  set_fact:
    isolcpus: "{{ isolcpus }}\
              ,{{ ansible_processor_cores + cmk_exclusive_num_cores }}\
              -{{ ansible_processor_vcpus - 1 }}"
  when:
    - cmk_exclusive_num_cores is defined
    - ansible_processor_count > 1
    - ansible_processor_threads_per_core == 1

# 58-83
- name: autogenerate isolcpu physical range for socket 2 hyperthread enabled
  set_fact:
    isolcpus: "{{ isolcpus }}\
              ,{{ ansible_processor_cores * ansible_processor_threads_per_core + cmk_exclusive_num_cores }}\
              -{{ ansible_processor_vcpus - ansible_processor_cores - 1 }}"
  when:
    - cmk_exclusive_num_cores is defined
    - ansible_processor_count > 1
    - ansible_processor_threads_per_core > 1

# 86-111
- name: autogenerate isolcpu logical range for socket 2 hyperthread enabled
  set_fact:
    isolcpus: "{{ isolcpus }}\
              ,{{ ansible_processor_vcpus - ansible_processor_cores + cmk_exclusive_num_cores }}\
              -{{ ansible_processor_vcpus  - 1 }}"
  when:
    - cmk_exclusive_num_cores is defined
    - ansible_processor_count > 1
    - ansible_processor_threads_per_core > 1

- name: print autogenerated isolcpus kernel command line argument
  debug:
    msg: "{{ isolcpus }}"
