# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: verify cadvisor daemonset
  check_k8s_object:
    name: cadvisor
    namespace: telemetry
    kind: daemonset
