# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2022 Intel Corporation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        sgx.intel.com/quote-provider: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: init-tmpfs
        image: "{{ .Values.apphsm.init.image.repo }}/{{ .Values.apphsm.init.image.name }}:{{ .Values.apphsm.init.image.tag }}"
        command: ['sh', '-c', "rm -rf /var/lib/softhsm/tokens/*"]
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.apphsm.main.image.repo }}/{{ .Values.apphsm.main.image.name }}:{{ .Values.apphsm.main.image.tag }}"
        imagePullPolicy: {{ .Values.apphsm.main.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-env-cm"
        volumeMounts:
        - name: mtls
          mountPath: /opt/intel/ca
          readOnly: true
        - name: sgx-qcnl-conf
          mountPath: /etc/sgx_default_qcnl.conf
          subPath: sgx_default_qcnl.conf
          readOnly: true
        - name: tmpfs
          mountPath: /tmp
          subPath: tmp
        - name: tmpfs
          mountPath: /var/lib/softhsm/tokens
          subPath: tokens
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: {{ .Values.apphsm.sgx_prv_gid }}
          readOnlyRootFilesystem: true
      - name: apphsm-rproxy
        image: "{{ .Values.apphsm.rproxy.image.repo }}/{{ .Values.apphsm.rproxy.image.name }}:{{ .Values.apphsm.rproxy.image.tag }}"
        imagePullPolicy: {{ .Values.apphsm.rproxy.image.pullPolicy }}
        ports:
        - name: apphsm-rproxy
          containerPort: {{ .Values.apphsm.rproxy.port }}
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx
            readOnly: true
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          runAsUser: 65334
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kmra
      volumes:
      - name: mtls
        secret:
          secretName: "{{ .Release.Name }}-tls"
          items:
          - key: tls.key
            path: apphsm.key
          - key: tls.cert
            path: apphsm.crt
          - key: ca.cert
            path: ca.crt
      - name: nginx-conf
        configMap:
          name: "{{ .Release.Name }}-rproxy-conf"
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: sgx-qcnl-conf
        configMap:
          name: "{{ .Release.Name }}-qcnl-conf"
      - name: tmpfs
        emptyDir:
          medium: Memory
          sizeLimit: 64Mi
