# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2022 Intel Corporation
---
- name: create tmp dir for keys-certs
  file:
    path: /opt/smartedge/kmra/mtls
    owner: "{{ ansible_user }}"
    group: "{{ project_group }}"
    mode: a=rx,u+w
    state: directory
  register: mtls_tmp_dir

- name: generate CA root crt
  command: >-
    openssl req -nodes -x509 -newkey rsa:2048
    -keyout {{ mtls_tmp_dir.path }}/ca.key
    -out {{ mtls_tmp_dir.path }}/ca.crt
    -subj "/O={{ kmra_ca_root_crt_subj.O }}/OU={{ kmra_ca_root_crt_subj.OU }}/CN={{ kmra_ca_root_crt_subj.CN }}"
  changed_when: true

- name: generate csr
  command: >-
    openssl req -nodes -newkey rsa:2048
    -keyout {{ mtls_tmp_dir.path }}/{{ item.name }}.key
    -out {{ mtls_tmp_dir.path }}/{{ item.name }}.csr
    -subj "/O={{ item.subj.O | default('') }}/OU={{ item.subj.OU | default('') }}/CN={{ kmra_apphsm_ip | default('') }}"
  loop: "{{ kmra_apps }}"
  changed_when: true
  when:
    - item.deploy

- name: generate certs
  command: >-
    openssl x509 -req -in {{ mtls_tmp_dir.path }}/{{ item.name }}.csr
    -CA {{ mtls_tmp_dir.path }}/ca.crt
    -CAkey {{ mtls_tmp_dir.path }}/ca.key
    {{ '-CAcreateserial' if ansible_loop.first }}
    {{ '-CAserial  ' + mtls_tmp_dir.path + '/ca.srl' if not ansible_loop.first }}
    -out {{ mtls_tmp_dir.path }}/{{ item.name }}.crt
  loop: "{{ kmra_apps }}"
  loop_control:
    extended: true
  changed_when: true
  when:
    - item.deploy

- name: create secrets for kmra apps
  command: >-
    kubectl create secret generic {{ item.name }}-tls
    --from-file=tls.cert={{ mtls_tmp_dir.path }}/{{ item.name }}.crt
    --from-file=tls.key={{ mtls_tmp_dir.path }}/{{ item.name }}.key
    --from-file=ca.cert={{ mtls_tmp_dir.path }}/ca.crt
    -n {{ kmra_namespace }}
  loop: "{{ kmra_apps }}"
  changed_when: true
  when:
    - item.deploy
