# INTEL CONFIDENTIAL
#
# Copyright 2021-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- name: setup hub cnf
  block:
    - name: copy file to the master node
      template:
        src: "{{ role_path }}/templates/values.yaml.j2"
        dest: "{{ sdewan_helm_charts_dir }}/sdewan-cnf/values.yaml"
        mode: a=rx,u+w
      with_items: "{{ cnf_config }}"
      become: yes

    - name: cnf helm install
      command: "{{ helm_cmd }} install sdewan-cnf ./sdewan-cnf/"
      args:
        chdir: "{{ sdewan_helm_charts_dir }}"
      become: yes

    - name: check the status of cnf pod
      shell: kubectl get deploy -n cnf | grep 0/1 | wc -l
      register: cnf_deploy
      retries: "{{ sdwan_number_of_retries }}"
      delay: "{{ sdwan_retry_delay }}"
      until: cnf_deploy.stdout | int == 0
      changed_when: false
      become: yes
  when: sdwan_labels is defined

- name: set ipsec tunnel
  block:
    - name: ipsec config with jinja2 template
      template:
        src: "{{ role_path }}/templates/ipsec_config.yaml.j2"
        dest: "{{ sdewan_helm_charts_dir }}/sdewan-cnf/ipsec_config.yaml"
        mode: a=rx,u+w
      with_items: "{{ cnf_config }}"
      become: yes

    - name: copy file to the master node
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: a=rx,u+w
      loop:
        - src: "{{ role_path }}/templates/ipsec_proposal.yaml.j2"
          dest: "{{ sdewan_helm_charts_dir }}/sdewan-cnf/ipsec_proposal.yaml"
      become: yes

    - name: check whether ipsec enable
      stat:
        path: "{{ sdewan_helm_charts_dir }}/sdewan-cnf/ipsec_config.yaml"
      register: sdewan_ipsec_enable
      become: yes

    - name: setup ipsec proposal
      command: "kubectl apply -f {{ item }}"
      args:
        chdir: "{{ sdewan_helm_charts_dir }}/sdewan-cnf"
      loop:
        - ipsec_proposal.yaml
      become: yes
      when:
        - sdewan_ipsec_enable.stat.size > {{ empty_file_size }}

    - name: wait for ipsec proposal up
      wait_for:
        timeout: 20
      become: yes
      when:
        - sdewan_ipsec_enable.stat.size > {{ empty_file_size }}

    - name: setup ipsec config
      command: "kubectl apply -f {{ item }}"
      args:
        chdir: "{{ sdewan_helm_charts_dir }}/sdewan-cnf"
      loop:
        - ipsec_config.yaml
      become: yes
      when:
        - sdewan_ipsec_enable.stat.size > {{ empty_file_size }}
  when:
    - sdwan_labels is defined
