# INTEL CONFIDENTIAL
#
# Copyright 2021-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

sdewan_crd_commit: EWO_v1.0
cert_link: "https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml"
helm_cmd: /usr/local/bin/helm
number_of_clean_retries: 1
clean_retry_delay: 2
sdwan_number_of_retries: 50
sdwan_retry_delay: 10
sdewan_helm_charts_dir: "{{ project_dir }}/sdewan/charts"
kubebuilder_link: "https://go.kubebuilder.io/dl/2.3.1/linux/amd64"
kubebuilder_download_name: "kubebuilder_2.3.1_linux_amd64"
kubebuilder_download_dest: "/tmp/{{ kubebuilder_download_name }}.tar.gz"
kubebuilder_tar_folder: "/tmp/{{ kubebuilder_download_name }}"
kubebuilder_bin_folder: "/usr/local/kubebuilder"
sdewan_crd_url: https://{{ git_repo_token }}@github.com/smart-edge-open/ewo
sdwan_crd_image: integratedcloudnative/sdewan-controller:dev
sdwan_crd_image_path: "{{ sdewan_helm_charts_dir }}/ewo/platform/crd-ctrlr/src"
sdwan_cnf_path: "{{ sdewan_helm_charts_dir }}/ewo/platform/cnf-openwrt/src"
sdwan_no_proxy: "localhost,120.0.0.1,192.168.*"
empty_file_size: 100
