# INTEL CONFIDENTIAL
#
# Copyright 2021-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
##################################################
##### ICN-SDWAN Settings
cni_version: 0.3.1
icn_sdwan_repo: "https://github.com/akraino-edge-stack/icn-sdwan" 
icn_sdwan_dir: "{{ project_dir }}/sdewan/"
icn_commit: prod-22.06
scc_image: scc
cnf_chart_name: icn-sdewan-cnf
crd_ctrl_chart_name: icn-sdewan-ctrl

sase_golang_version: 1.17
sase_golang_download_name: "go{{ sase_golang_version }}.linux-amd64.tar.gz"
sase_golang_download_url_base: "https://dl.google.com/go/"
sase_golang_download_url: "{{ sase_golang_download_url_base }}{{ sase_golang_download_name }}"
sase_golang_download_dest: "{{ icn_sdwan_dir }}/golang/"
sase_golang_download_checksum: "sha256:6bf89fc4f5ad763871cf7eac80a2d594492de7a818303283f1366a7f6a30372d"

network_conf:
  # Default Configuration
  - pnets: 
      - network_name: pnetwork
        subnet_name: subnet
        vlanID: 301
        network_cidr: "10.10.70.0/24"
  # Add customized configuration here, e.g. 
      # - network_name: pnetwork2
      #   subnet_name: subnet2
      #   vlanID: 302
      #   network_cidr: "10.20.70.0/24"
    onets:
      - network_name: ovn-network
        subnet_name: subnet1
        network_cidr: "172.16.70.0/24"
  # Add customized configuration here, e.g. 
      # - network_name: ovn-network2
      #   subnet_name: subnet2
      #   network_cidr: "172.16.70.0/24"

#network_firewallrule:
#  - rules:
#      - name: "firewallrule-sample" # you can customize
#        namespace: "sdewan-system"  # sdewan safe cnf namespace
#        sdewanPurpose: "base"       # sdewan safe cnf sdewanPurpose
#        src: "eth0"  # network card name. Both pyhsical and virtual cark are ok
#        src_ip: "192.168.100.0"
#        src_port: "80"
#        proto: "tcp" # Can be one of tcp, udp, tcpudp, udplite, icmp, esp, ah, sctp, or all
#        dest: "eth0"
#        dest_ip: "192.168.100.1"
#        dest_port: "80"
#        target: "ACCEPT"  #(Required) Firewall action (ACCEPT, REJECT, DROP, MARK, NOTRACK) for matched traffic
##################################################
