# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: install os packages
  include_tasks: install_os_packages.yml
  when: install_dependencies is defined

- name: install python packages
  include_tasks: install_pip_packages.yml
  when: install_python_dependencies is defined
