# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

_kubernetes_env_file: ""
_kubernetes_config_dir: "/tmp/k8s_deploy_configs"
_kubernetes_config_file: "{{ _kubernetes_config_dir }}/kubelet_config.yaml"

cpu:
  policy: "static"  # Options: none (disabled), static (default)
  reserved_cpus: 1

topology_manager:
  policy: "best-effort"  # Options: none (disabled), best-effort (default), restricted, single-numa-node
