# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: create default network policies
  block:
    - name: create temp dir
      tempfile:
        state: directory
        suffix: -default-net-pol
      register: tmp_dir

    - name: create default smart edge network policies
      template:
        src: "{{ item }}"
        dest: "{{ tmp_dir.path }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
        mode: preserve
      with_fileglob: "../templates/*.j2"

    - name: copy default network policy
      copy:
        src: default-network-policy.yaml
        dest: "{{ tmp_dir.path }}/default-network-policy.yaml"
        mode: preserve

    - name: apply default network policies
      command: kubectl apply -f "{{ tmp_dir.path }}"
      changed_when: true
