# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: load sr-iov operator default vars
  include_vars: ../defaults/main.yml

- name: check sr-iov deployments
  check_k8s_object:
    kind: deployment
    name: "sriov-network-operator"
    namespace: "{{ sriov_network_operator_namespace }}"

- name: check sr-iov operator daemonset
  check_k8s_object:
    kind: daemonset
    name: "{{ item }}"
    namespace: "{{ sriov_network_operator_namespace }}"
  loop:
  - network-resources-injector
  - operator-webhook
  - sriov-device-plugin
  - sriov-network-config-daemon
  
