# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
- name: Set variable for installing NFS server
  set_fact:
    install_nfs_server: "{{ \
      isecl_nfs_server is undefined \
      or isecl_nfs_server | length == 0 \
      or isecl_nfs_server == hostvars[inventory_hostname].ansible_host \
      or isecl_nfs_server == hostvars[inventory_hostname].ansible_hostname \
      }}"

- name: Update NFS server IP
  set_fact:
    isecl_nfs_server: "{{ hostvars[inventory_hostname].ansible_host }}"
  when: install_nfs_server

# Internal IP of cloud(AWS) instance is needed for control-plane services to communicate with NFS
- name: Update internal ip of cloud instance for verification controller deployment
  block:
    - name: Get NFS server internal ip
      shell: hostname -I | awk '{print $1}'
      register: nfs_server_internal_ip
      changed_when: false
    - name: Update NFS server internal ip in case of verification controller deployment
      set_fact:
        isecl_nfs_server: "{{ nfs_server_internal_ip.stdout }}"
        isecl_control_plane_internal_ip: "{{ nfs_server_internal_ip.stdout }}"
  when: platform_attestation_controller | default(False)

- name: Create folder structure in NFS directory
  command: "./setup-nfs.sh {{ isecl_nfs_server_dir }} {{ isecl_user_id }} {{ isecl_nfs_server }}"
  args:
    chdir: "{{ isecl_helm_charts_dir }}"
  changed_when: false
  become: true

- name: Setup NFS server
  include_role:
    name: infrastructure/install_nfs_server
  vars:
    nfs_dir_path: "{{ isecl_nfs_server_dir }}"
    nfs_clients: "{{ isecl_nfs_server_clients | default([]) + [ isecl_nfs_server ] }}"
  when: install_nfs_server

- name: Setup NFS client
  include_role:
    name: infrastructure/install_nfs_client
  vars:
    nfs_server: "{{ isecl_nfs_server }}"
    nfs_client_share_dir: "{{ isecl_nfs_client_mount_path }}"
    nfs_server_dir: "{{ isecl_nfs_server_dir }}"

