# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
- name: Set variable for installing NFS server
  set_fact:
    install_nfs_server: "{{ \
      isecl_nfs_server is undefined \
      or isecl_nfs_server | length == 0 \
      or isecl_nfs_server == hostvars[inventory_hostname].ansible_default_ipv4.address \
      or isecl_nfs_server == hostvars[inventory_hostname].ansible_hostname \
      }}"

- name: Update NFS server IP
  set_fact:
    isecl_nfs_server: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
  when: install_nfs_server

- name: Create folder structure in NFS directory
  command: "./setup-nfs.sh {{ isecl_nfs_server_dir }} {{ isecl_user_id }} {{ isecl_nfs_server }}"
  args:
    chdir: "{{ isecl_helm_charts_dir }}"
  changed_when: false
  become: true

- name: Setup NFS server
  include_role:
    name: infrastructure/install_nfs_server
  vars:
    nfs_dir_path: "{{ isecl_nfs_server_dir }}"
    nfs_clients: "{{ isecl_nfs_server_clients | default([]) + [ isecl_nfs_server ] }}" 
  when: install_nfs_server

- name: Setup NFS client
  include_role:
    name: infrastructure/install_nfs_client
  vars:
    nfs_server: "{{ isecl_nfs_server }}"
    nfs_client_share_dir: "{{ isecl_nfs_client_mount_path }}"
    nfs_server_dir: "{{ isecl_nfs_server_dir }}"

