# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: setup repository
  include_tasks: setup_repository.yml

- name: install kernel dependencies - URLs
  yum:
    name: "{{ kernel_dependencies_urls | join(',') }}"
    state: present
    allow_downgrade: true
  retries: "{{ number_of_retries }}"
  delay: "{{ retry_delay }}"
  become: yes

- name: install kernel dependencies - packages
  yum:
    name: "{{ kernel_dependencies_packages | join(',') }}"
    state: present
    allow_downgrade: true
  retries: "{{ number_of_retries }}"
  delay: "{{ retry_delay }}"
  become: yes

- name: get current CMDLINE
  command: cat /proc/cmdline
  register: current_cmdline
  changed_when: false

- name: install kernel and kernel devel for non calico-ebpf
  block:
    - name: install kernel and kernel devel non calico-ebpf
      yum:
        name: "{{ kernel_package }}-{{ kernel_version }},{{ kernel_devel_package }}-{{ kernel_version }}"
        state: present
        disable_excludes: all
      retries: "{{ number_of_retries }}"
      delay: "{{ retry_delay }}"
      become: yes

    - name: set kernel as default
      command: grubby --set-default /boot/vmlinuz-{{ kernel_version }}
      changed_when: true
      become: yes

    # role `conditional_reboot` checks if `perform_reboot` is defined, is so machine is rebooted
    - name: request reboot (will be performed by `conditional_reboot` role) non calico-ebpf
      set_fact:
        perform_reboot: "{{ perform_reboot|default([]) + [ 'kernel' ] }}"
      when: kernel_version not in current_cmdline.stdout
  when: not ( calico_ebpf_enabled | default(false))

- name: install ebpf ml kernel, kernel devel and reboot for calico-ebpf
  block:
    - name: install ebpf longterm ml kernel devel for calico-ebpf
      command: yum -y --enablerepo=elrepo-kernel install kernel-lt.x86_64 kernel-lt-devel.x86_64
      args:
        warn: false
      register: temp_out
      become: yes

    - name: get longterm mainline kernel version for calico-ebpf
      shell: yum list available --disablerepo='*' --enablerepo=elrepo-kernel | grep -m 1 "kernel-lt" | awk '{ print $2".x86_64"}'
      args:
        warn: false
      register: ebpf_kernel_version
      become: yes

    - name: set kernel as default
      command: grubby --set-default /boot/vmlinuz-{{ ebpf_kernel_version.stdout }}
      changed_when: true
      become: yes

    # role `conditional_reboot` checks if `perform_reboot` is defined, is so machine is rebooted
    - name: request reboot (will be performed by `conditional_reboot` role) for calico-ebpf
      set_fact:
        perform_reboot: "{{ perform_reboot|default([]) + [ 'kernel' ] }}"
      when: ebpf_kernel_version.stdout not in current_cmdline.stdout
  when: calico_ebpf_enabled | default(false)
