# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    sdewanPurpose: {{ .Values.metadata.labels }}
spec:
  progressDeadlineSeconds: {{ .Values.spec.progressDeadlineSeconds }}
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      sdewanPurpose: {{ .Values.metadata.labels }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.plugin.opnfv.org/nfn-network: |-
          { "type": "ovn4nfv", "interface": [
          {{- range .Values.nfn }} {{- with . }}
            {
              "defaultGateway": "{{- .defaultGateway -}}",
              "interface": "{{- .interface -}}",
              "ipAddress": "{{- .ipAddress -}}",
              "name": "{{- .name -}}",
              "namespace": "{{- .namespace -}}"
            } {{- .separate -}} 
            {{- end }} {{- end }}
          ]}
        k8s.v1.cni.cncf.io/networks: '[{ "name": "ovn4nfv-k8s-plugin"}]'
      labels:
        sdewanPurpose: {{ .Values.metadata.labels }}
        cnf-account-secret: {{ .Values.metadata.passwdSecret }}
        cnf-cert-secret: {{ .Values.metadata.cert }}
    spec:
      containers:
      - command:
              #- sleep
              #- "3600"
        - /usr/bin/sudo
        - /bin/sh
        - /tmp/sdewan/entrypoint.sh
        image: {{ .Values.containers.image }}
        imagePullPolicy: {{ .Values.containers.imagePullPolicy }}
        name: {{ .Values.containers.name }}
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          privileged: true
          procMount: Default
        volumeMounts:
        - mountPath: /tmp/sdewan
          name: sdewan-safe-sh
          readOnly: true
        - mountPath: /tmp/podinfo
          name: podinfo
          readOnly: true
        - mountPath: /tmp/sdewan/serving-certs
          name: cert
          readOnly: true
        - mountPath: /tmp/sdewan/account
          name: account
          readOnly: true
      nodeSelector:
        node-role.kubernetes.io/master: "{{ .Values.nodeSelector }}"
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
      - configMap:
          defaultMode: 420
          name: sdewan-safe-sh
        name: sdewan-safe-sh
      - name: podinfo
        downwardAPI:
          items:
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ .Values.metadata.cert }}
      - name: account
        secret:
          defaultMode: 420
          secretName: {{ .Values.metadata.passwdSecret }}