# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
- name: Create Secrets for ISecL Scheduler TLS Key-pair
  block:
  - name: Create temporary dir
    tempfile:
      state: directory
      suffix: sched-tls-cert
    register: isecl_sched_tls_cert_temp_dir

  - name: Create openssl csr request
    command: openssl req -new -days 365 -newkey rsa:4096 -addext "subjectAltName = DNS:{{ isecl_k8s_control_plane_hostname }}" -nodes -text -out server.csr -keyout server.key -sha384 -subj "/CN=ISecl Scheduler TLS Certificate"
    args:
      chdir: "{{ isecl_sched_tls_cert_temp_dir.path }}"

  - name: Create k8s CSR object
    shell: |
      cat <<EOF | kubectl apply -f -
      apiVersion: certificates.k8s.io/v1
      kind: CertificateSigningRequest
      metadata:
        name: isecl-scheduler.isecl
      spec:
        request: $(cat server.csr | base64 | tr -d '\n')
        signerName: kubernetes.io/kube-apiserver-client
        usages:
        - client auth
      EOF
    args:
      chdir: "{{ isecl_sched_tls_cert_temp_dir.path }}"

  - name: Approve k8s certificate
    command: kubectl certificate approve isecl-scheduler.isecl
      
  - name: Get k8s server certificate
    shell: kubectl get csr isecl-scheduler.isecl -o jsonpath='{.status.certificate}' | base64 --decode > server.crt
    args:
      chdir: "{{ isecl_sched_tls_cert_temp_dir.path }}"

  - name: Create k8s secret
    command: kubectl create secret tls isecl-scheduler-certs --cert={{ isecl_sched_tls_cert_temp_dir.path }}/server.crt --key={{ isecl_sched_tls_cert_temp_dir.path }}/server.key -n isecl
    args:
      chdir: "{{ isecl_sched_tls_cert_temp_dir.path }}"

