# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
- name: Create Secrets for ISecL Admission controller secrets
  block:
  - name: Create temporary dir
    tempfile:
      state: directory
      suffix: admission-tls-cert
    register: isecl_adm_tls_cert_temp_dir

  - name: Create openssl csr request
    command: openssl req -new -days 365 -newkey rsa:4096 -addext "subjectAltName = DNS:admission-controller.isecl.svc" -nodes -text -out server.csr -keyout server.key -sha384 -subj "/CN=system:node:{{ isecl_k8s_control_plane_hostname }};/O=system:nodes"
    args:
      chdir: "{{ isecl_adm_tls_cert_temp_dir.path }}"

  - name: Create k8s CSR object
    shell: |
      cat <<EOF | kubectl apply -f -
      apiVersion: certificates.k8s.io/v1
      kind: CertificateSigningRequest
      metadata:
        name: admission-controller.isecl
      spec:
        groups:
        - system:authenticated
        request: $(cat server.csr | base64 | tr -d '\n')
        signerName: kubernetes.io/kubelet-serving
        usages:
        - digital signature
        - key encipherment
        - server auth
      EOF
    args:
      chdir: "{{ isecl_adm_tls_cert_temp_dir.path }}"

  - name: Approve k8s certificate
    command: kubectl certificate approve admission-controller.isecl
      
  - name: Get k8s server certificate
    shell: kubectl get csr admission-controller.isecl -o jsonpath='{.status.certificate}' | base64 --decode > server.crt
    args:
      chdir: "{{ isecl_adm_tls_cert_temp_dir.path }}"

  - name: Create k8s secret
    command: kubectl create secret tls admission-controller-certs --cert={{ isecl_adm_tls_cert_temp_dir.path }}/server.crt --key={{ isecl_adm_tls_cert_temp_dir.path }}/server.key -n isecl
    args:
      chdir: "{{ isecl_adm_tls_cert_temp_dir.path }}"

