# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
openssl_certs_mapping:
  - {openssl_dir: /usr/local/ssl/certs, linux_dir: /etc/ssl/certs}
  - {openssl_dir: /usr/local/ssl/private, linux_dir: /etc/ssl/private}
