# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

# Service Mesh Interface (SMI) operator for Istio
# https://github.com/servicemeshinterface/smi-adapter-istio

- name: apply SMI crds, operator, and rbac configuration
  command: kubectl apply -f "{{ item }}"
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"
  changed_when: true
  loop:
    - "{{ _smi_crds_yaml }}"
    - "{{ _smi_operator_yaml }}"

- name: wait for smi-adapter-istio pod to become running
  command: >
    kubectl wait --for=condition=ready pod -l name=smi-adapter-istio -n istio-system
    --timeout={{ number_of_retries * 2 * retry_delay }}s
  changed_when: false
