# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: import elrepo gpg key
  become: yes
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: install elrepo repository for RedHat 7
  become: yes
  package:
    name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
    state: present
  when:
    - ansible_distribution_version < '8'

- name: install elrepo repository for RedHat 8
  become: yes
  package:
    name: https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    state: present
  when:
    - ansible_distribution_version >= '8'
