# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2021 Intel Corporation

---
# Common platform setup playbook
- hosts: controller_group:edgenode_group
  any_errors_fatal: true

  handlers:
    - import_tasks: "{{ playbook_dir }}/../tasks/reboot_server.yml"

  roles:
    - role: infrastructure/setup_baseline_ansible
    - role: infrastructure/build_noproxy
    - role: baseline_ansible/infrastructure/os_proxy
    - role: baseline_ansible/infrastructure/time_setup_ntp
      when: ntp_enable | default(False)
    - role: infrastructure/os_setup
    - role: infrastructure/check_redeployment
    - role: baseline_ansible/infrastructure/time_verify_ntp
      reference_host: "{{ groups['controller_group'][0] }}"
      when: "'edgenode_group' in group_names and not (ptp_sync_enable | default(False))"
    - role: baseline_ansible/infrastructure/install_rt_package
      when: kernel_rt_enable | default(False)
    - role: baseline_ansible/infrastructure/install_tuned_rt_profile
      when: tuned_enable | default(False)
    - role: infrastructure/install_hwe_kernel
    - role: baseline_ansible/infrastructure/configure_sriov_kernel_flags
      when: "iommu_enabled | default(True)"
    - role: baseline_ansible/infrastructure/configure_hugepages
      when: "hugepages_enabled | default(False)"
    - role: baseline_ansible/infrastructure/configure_cpu_idle_driver
      when: "cpu_idle_driver_setup_enabled | default(False)"
    - role: baseline_ansible/infrastructure/configure_cpu_isolation
      when: "isolcpus_enabled | default(False)"
    - role: baseline_ansible/infrastructure/configure_additional_grub_parameters
      when: "additional_grub_parameters_enabled | default(False)"

    - role: infrastructure/conditional_reboot
    - role: infrastructure/e810_driver_update
      when: e810_driver_enable | default(False)
    - role: baseline_ansible/infrastructure/install_userspace_drivers
      when: install_userspace_drivers_enable | default(False)

    - role: infrastructure/provision_sgx_enabled_platform
      when: sgx_enabled | default(False)

    - role: infrastructure/git_repo_tool
      when: "platform_attestation_controller | default(False) or platform_attestation_node | default(False)"

    - role: baseline_ansible/infrastructure/install_golang
      golang_additional_exports:
        - "export GOPRIVATE=github.com/smart-edge-open"
    - role: infrastructure/docker

- hosts: controller_group
  any_errors_fatal: true
  roles:
    - role: infrastructure/ptp/controlplane
      when: ptp_sync_enable | default(False)

- hosts: edgenode_group
  any_errors_fatal: true
  roles:
    - role: infrastructure/ptp/node
      when: ptp_sync_enable | default(False)
    - role: baseline_ansible/infrastructure/time_verify_ntp
      reference_host: "{{ groups['controller_group'][0] }}"
      when: ptp_sync_enable | default(False)
