# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
- name: Create temporary directory for PCCS build&installation
  tempfile:
    state: directory
  register: temp_dir

- name: Clone PCCS repo
  git:
    repo: "{{ _pccs_repo }}"
    dest: "{{ temp_dir.path }}"
    version: "{{ _pccs_version }}"

- name: Build docker image
  docker_image:
    name: "{{ _pccs_image_name }}"
    tag: "{{ _pccs_image_tag }}"
    source: build
    build:
      path: "{{ temp_dir.path }}/QuoteGeneration/pccs/container"
      pull: true

- name: Create {{ _pccs_namespace }} namespace if doesn't exist
  include_role:
    name: baseline_ansible/kubernetes/custom_namespace
  vars:
    - _custom_ns: ["{{ _pccs_namespace }}"]

- name: Generate certificates for PCCS
  include_role:
    name: kubernetes/certs
  vars:
    tls_secret_name: "{{ _pcss_certificate_secret_name }}"
    desired_namespace: "{{ _pccs_namespace }}"
    dns_names: ["pccs"]

- name: Create charts directory
  file:
    state: directory
    path: "{{ _pcss_chart_dir }}"
    mode: u+rwx

- name: Copy helm chart files
  copy:
    src: "{{ item }}"
    dest: "{{ _pcss_chart_dir }}" 
    directory_mode: u+rwx
    mode: u+rw
  loop:
    - Chart.yaml
    - templates

- name: Template values.yml
  template:
    src: values.yml
    dest: "{{ _pcss_chart_dir }}/values.yml"
    mode: u+rw

- name: Install PCCS
  command: helm install --namespace={{ _pccs_namespace }} pccs -f "{{ _pcss_chart_dir }}/values.yml" {{ _pcss_chart_dir }}
  changed_when: yes
