# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: IP_AUTODETECTION_METHOD
    value: "can-reach=8.8.8.8"
