# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

resources:
- calico.yml

patchesStrategicMerge:
- change_cidr.yml
- customize_calico_conf.yml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: calico-node
  path: customize_calico_container.yml
