# Copyright (C) 2021  Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.basename }}-config-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistentVolumeConfig.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentVolumeConfig.requests.storage }}
