# Copyright (C) 2021  Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.basename }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    env: test
    app: {{ .Values.basename }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.basename }}
  template:
    metadata:
      labels:
        app: {{ .Values.basename }}
    spec:
      securityContext:
        fsGroup: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.basename }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.basename }}-config
          env:
            {{- toYaml .Values.proxyConfig | nindent 12 }}
          volumeMounts:
            - name: ihub-config-volume
              mountPath: {{ .Values.volumeConfig.ihubConfigPath }}
            - name: ihub-k8s-certs
              mountPath: /apiserver.crt
              subPath: apiserver.crt
            - name: ihub-logs-volume
              mountPath: {{ .Values.volumeConfig.ihubLogsPath }}
            - mountPath: {{ .Values.volumeConfig.ihubSecretsPath }}
              name: ihub-secrets
              readOnly: true
      volumes:
        - name: ihub-k8s-certs
          secret:
            secretName: ihub-k8s-certs
            defaultMode: 0640
        - name: ihub-logs-volume
          persistentVolumeClaim:
            claimName: ihub-logs-pvc
        - name: ihub-config-volume
          persistentVolumeClaim:
            claimName: ihub-config-pvc
        - name: ihub-secrets
          projected:
            sources:
              - secret:
                  name: ihub-credentials
              - secret:
                  name: bearer-token
