# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ihub-credentials
  namespace: isecl
stringData:
  IHUB_SERVICE_USERNAME: ""
  IHUB_SERVICE_PASSWORD: ""
