# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: remove Go files
  file:
    path: "{{ golang_download_dest }}"
    state: absent
  become: yes

- name: remove exports from /etc/profile
  file:
    path: /etc/profile.d/golang.sh
    state: absent
  become: yes
