# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
- name: get installed golang version
  command: "cat /usr/local/go/VERSION"
  ignore_errors: true
  register: go_version_file_cat
  changed_when: false

- name: set expected golang version as in VERSION file
  set_fact:
    golang_version_fullname: "{{ 'go' + (golang_version | string) }}"

- name: install or update package
  include_tasks: install.yml
  when: golang_version_fullname != go_version_file_cat.stdout

- name: install packages
  include_tasks: install_packages.yml
