# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

# SR-IOV Network Operator repo values
_sriov_network_operator:
  url: "https://github.com/k8snetworkplumbingwg/sriov-network-operator"
  download_dir: "{{ _sriov_network_operator_root_dir }}/src"
  version: "v1.1.0"
  image_tag: "4.9.0"
  resource_prefix: "intel.com"
  enable_admission_controller: "true"
  git_patch: "sriov_network_operator.patch"
  git_webhook_patch: "sriov_no_webhook.patch"

# Webhooks certificates values
_sriov_network_operator_certs_dest: "{{ project_dir }}/certs/sriov-network-operator"
_sriov_network_operator_ca_certs_dest: "{{ _sriov_network_operator_certs_dest }}/CA"
_webhook_operator_service_certs_dir: "{{ _sriov_network_operator_certs_dest }}/webhook-operator-service"
_network_resources_injector_certs_dir: "{{ _sriov_network_operator_certs_dest }}/network-resources-injector"

# general variables
makefile_env_path_var: "/usr/local/go/bin:{{ ansible_env.PATH }}"
patching_retries: 30
patching_delay: 10
